version: 1
builder:
  configs:
    - swift_version: 5.9
      documentation_targets: [OpenSwiftUI]
      customDocumentationParameters: [
        --source-service, github,
        --source-service-base-url, https://github.com/Kyle-Ye/OpenSwiftUI/blob/main,
        --checkout-path, .
      ]
