name: iOS 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ios_test:
    name: Execute tests on iOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            xcode-version: "15.3"   # Swift 5.10
    runs-on: ${{ matrix.os }}
    env:
      OPENSWIFTUI_WERROR: 1
      OPENSWIFTUI_SWIFT_TESTING: 1
      OPENGRAPH_ATTRIBUTEGRAPH: 1
      OPENSWIFTUI_COMPATIBILITY_TEST: 0
      OPENSWIFTUI_SWIFT_LOG: 0
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Build in release mode
        run: |
          xcodebuild build \
            -scheme OpenSwiftUI \
            -configuration Debug \
            -destination "platform=iOS-Simulator" \
            -skipMacroValidation \
            -skipPackagePluginValidation
      - name: Build and run tests in debug mode
        run: |
          xcodebuild test \
            -scheme OpenSwiftUI \
            -configuration Debug \
            -destination "platform=iOS-Simulator" \
            -skipMacroValidation \
            -skipPackagePluginValidation
