name: iOS 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ios_test:
    name: Execute tests on iOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            xcode-version: "15.1"   # Swift 5.9.2
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Build in release mode
        run: |
          xcodebuild build \
            -scheme OpenSwiftUI \
            -configuration Debug \
            -skipMacroValidation -skipPackagePluginValidation \
            -destination "platform=iOS-Simulator" \
            # OpenSwiftUI-Package is not listed currently
            # OTHER_SWIFT_FLAGS="-warnings-as-errors" \ AccessLevelOnImport will cause build warning via xcodebuild
      - name: Build and run tests in debug mode
        run: |
          xcodebuild test \
            -scheme OpenSwiftUI \
            -configuration Debug \
            -skipMacroValidation -skipPackagePluginValidation \
            -destination "platform=iOS-Simulator" \
            # OTHER_SWIFT_FLAGS="-warnings-as-errors"