name: macOS 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_test:
    name: Execute tests on macOS
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            xcode-version: "15.3"   # Swift 5.10
    runs-on: ${{ matrix.os }}
    env:
      OPENSWIFTUI_WERROR: 1
      OPENSWIFTUI_SWIFT_TESTING: 1
      OPENGRAPH_ATTRIBUTEGRAPH: 1
      OPENSWIFTUI_COMPATIBILITY_TEST: 0
      OPENSWIFTUI_SWIFT_LOG: 0
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Build and run tests in debug mode with coverage
        run: |
          swift test \
            -c debug \
            --filter OpenSwiftUITests \
            -Xswiftc -warnings-as-errors \
            --enable-code-coverage \
            --build-path .build-test-debug
          xcrun llvm-cov show \
            -instr-profile=.build-test-debug/debug/codecov/default.profdata \
            .build-test-debug/debug/OpenSwiftUIPackageTests.xctest/Contents/MacOS/OpenSwiftUIPackageTests \
            > coverage.txt
      - name: Build and run tests in release mode
        run: |
          swift test \
            -c release \
            --filter OpenSwiftUITests \
            -Xswiftc -warnings-as-errors \
            --enable-code-coverage \
            --build-path .build-test-release
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
