name: Wasm 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wasmer_test:
    name: Execute tests on WASM
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["wasm-5.9.1-RELEASE", "wasm-5.10-SNAPSHOT-2024-01-22-a", "wasm-DEVELOPMENT-SNAPSHOT-2024-01-22-a"]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: ${{ matrix.swift_version }}
      - name: build
        run: |
          swift build
      - name: test
        run: |
          swift test