name: Wasm 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wasm_test:
    name: Execute tests on WASM
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.10-RELEASE"]
        os: [ubuntu-22.04]
        extra_params: []
    runs-on: ${{ matrix.os }}
    env:
      OPENSWIFTUI_WERROR: 1
      OPENSWIFTUI_SWIFT_TESTING: 0
      OPENGRAPH_ATTRIBUTEGRAPH: 0
      OPENSWIFTUI_COMPATIBILITY_TEST: 0
      OPENSWIFTUI_SWIFT_LOG: 1
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: wasm-${{ matrix.swift_version }}
      - name: build
        run: |
          swift build --triple wasm32-unknown-wasi ${{ matrix.extra_params }}
      # Blocked by upstream support for WASM. See https://github.com/apple/swift-testing/issues/228
      # - name: test
      #   run: |
      #     swift test --triple wasm32-unknown-wasi ${{ matrix.extra_params }}